import type { NextPage } from "next";
import Head from "next/head";
import Home from "../views/Home";

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Home />
      </main>
    </>
  );
};

export default HomePage;
