import type { NextPage } from "next";
import Head from "next/head";
import Favorites from "../../views/Favorites";

const FavoritesPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Favorites</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Favorites />
      </main>
    </>
  );
};

export default FavoritesPage;
