import type { NextPage } from "next";
import Head from "next/head";

const Movies: NextPage = () => {
  return (
    <>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Pagina de detalhes</main>
    </>
  );
};

export default Movies;
